travis:
  secure:
    BINSTAR_TOKEN: NjQWapZ0yFmnFumAnhFsofo9/PpR2fAPxfQPtynncVAwvW+bMPTCICiCcmkThOR9VfFuih82+Zgfwdet7JAIOReZE/b/F7KL8AOfp6rgauGucjg8p6EINfdH5kMlCDsFASsXgd5yeWUfL9ACSfkK8NnXk5arnCBr74eCnSUSI/p4jbA2hnGISehTgAySKy7bHGUl+vxv6HBcjtUw5KQpz0BW3/iN6Od/+Tm5MfpZuybAXJTMeNbninzxYCQNUA4kbjfBtoau4uwb0LxNY19OemFGuNd0Xk/OCNYxhZRVq4Qof7KcZnLRrLdpx5QUN3vfJb7o5y3rOkibvIUouYzzJBMsYhWpfs2mxiaW5nXghwzm/A4V6r2hyqy7sDtMNkFxS+/1i2T8Yd0bysKRhX2H1BXCPSIk3+ncSOvqZo6wpHOimh1D2QhrRwYceCd7xwdsOZYyWjh1EOQvEu23s2pI1qzZ5/JDkuwecY2CFgh90/Q90K+cGiAC9lT+HHvsmkASjtM2yHLuyJ/uIg7RDhxZKxm9AoDxgtIKOLrjpCYhbGSJ0k+PtW71tvXJWyohgAnNEinzglmYxnF9XhlsCuVKCLRhKO27gUVa++Xt9eHcK/81tHNi8DW539Npkv9kxAhw7ecxqH3znxSAM0se3pMADoyZpBhB8EC/5QOB7anarQI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
